netbox_kea/urls.py
from django.urls import include, path
from utilities.urls import get_model_urls

from . import views

urlpatterns = (
    path("servers/", views.ServerListView.as_view(), name="server_list"),
    path("servers/add/", views.ServerEditView.as_view(), name="server_add"),
    path(
        "servers/delete/",
        views.ServerBulkDeleteView.as_view(),
        name="server_bulk_delete",
    ),
    path(
        "servers/<int:pk>/leases6/delete/",
        views.ServerLeases6DeleteView.as_view(),
        name="server_leases6_delete",
    ),
    path(
        "servers/<int:pk>/leases4/delete/",
        views.ServerLeases4DeleteView.as_view(),
        name="server_leases4_delete",
    ),
    path("servers/<int:pk>/", include(get_model_urls("netbox_kea", "server"))),
)

netbox_kea/forms.py
from typing import Any, Literal

from django import forms
from django.core.exceptions import ValidationError
from netaddr import EUI, AddrFormatError, IPAddress, IPNetwork, mac_unix_expanded
from netbox.forms import NetBoxModelFilterSetForm, NetBoxModelForm
from utilities.forms import BOOLEAN_WITH_BLANK_CHOICES
from utilities.forms.fields import TagFilterField

from . import constants
from .models import Server
from .utilities import is_hex_string


class ServerForm(NetBoxModelForm):
    class Meta:
        model = Server
        fields = (
            "name",
            "server_url",
            "username",
            "password",
            "ssl_verify",
            "client_cert_path",
            "client_key_path",
            "ca_file_path",
            "dhcp6",
            "dhcp4",
            "tags",
        )
        widgets = {
            "password": forms.PasswordInput(),
        }


class VeryHiddenInput(forms.HiddenInput):
    """Returns an empty string on render."""

    input_type = "hidden"
    template_name = ""

    def render(self, name: str, value: Any, attrs: Any, renderer: Any) -> str:
        return ""


class ServerFilterForm(NetBoxModelFilterSetForm):
    model = Server
    tag = TagFilterField(model)
    dhcp4 = forms.NullBooleanField(
        label="DHCPv4",
        required=False,
        widget=forms.Select(choices=BOOLEAN_WITH_BLANK_CHOICES),
    )
    dhcp6 = forms.NullBooleanField(
        label="DHCPv6",
        required=False,
        widget=forms.Select(choices=BOOLEAN_WITH_BLANK_CHOICES),
    )


class BaseLeasesSarchForm(forms.Form):
    q = forms.CharField(label="Search")
    page = forms.CharField(required=False, widget=VeryHiddenInput)

    def clean(self) -> dict[str, Any] | None:
        ip_version = self.Meta.ip_version
        cleaned_data = super().clean()
        q = cleaned_data.get("q")
        by = cleaned_data.get("by")

        if q and not by:
            raise ValidationError({"by": "Search attribute is empty."})
        elif by and not q:
            raise ValidationError({"q": "Search value is empty."})

        if by == constants.BY_SUBNET:
            try:
                if "/" not in q:
                    raise ValidationError({"q": "CIDR mask is required"})
                net = IPNetwork(q, version=ip_version)
                if net.ip != net.cidr.ip:
                    raise ValidationError(
                        {"q": f"{net} is not a valid prefix. Did you mean {net.cidr}?"}
                    )
                cleaned_data["q"] = net
            except (AddrFormatError, TypeError, ValueError) as e:
                raise ValidationError({"q": f"Invalid IPv{ip_version} subnet."}) from e
        elif by == constants.BY_SUBNET_ID:
            try:
                i = int(q)
                if i <= 0:
                    raise ValidationError({"q": "Invalid subnet ID."})
                cleaned_data["q"] = i
            except ValueError as e:
                raise ValidationError({"q": "Subnet ID must be an integer."}) from e
        elif by == constants.BY_IP:
            try:
                # use IPAddress to normalize values
                cleaned_data["q"] = str(IPAddress(q, version=ip_version))
            except (AddrFormatError, TypeError, ValueError) as e:
                raise ValidationError({"q": f"Invalid IPv{ip_version} address."}) from e
        elif by == constants.BY_HW_ADDRESS:
            try:
                cleaned_data["q"] = str(EUI(q, version=48, dialect=mac_unix_expanded))
            except (AddrFormatError, TypeError, ValueError) as e:
                raise ValidationError({"q": "Invalid hardware address."}) from e
        elif by == constants.BY_DUID:
            if not is_hex_string(
                q, constants.DUID_MIN_OCTETS, constants.DUID_MAX_OCTETS
            ):
                raise ValidationError({"q": "Invalid DUID."})
            cleaned_data["q"] = q.replace("-", "")
        elif by == constants.BY_CLIENT_ID:
            if not is_hex_string(
                q, constants.CLIENT_ID_MIN_OCTETS, constants.DUID_MAX_OCTETS
            ):
                raise ValidationError({"q": "Invalid client ID."})
            cleaned_data["q"] = q.replace("-", "")

        page = cleaned_data["page"]
        if page:
            if by != constants.BY_SUBNET:
                raise ValidationError({"page": "page is only supported with subnet."})
            try:
                page_ip = IPAddress(page, version=ip_version)
                if page_ip not in cleaned_data["q"]:
                    raise ValidationError({"page": "page is not in the given subnet"})

                cleaned_data["page"] = str(page_ip)
            except AddrFormatError as e:
                raise ValidationError({"page": "Invalid IP."}) from e


class Leases4SearchForm(BaseLeasesSarchForm):
    by = forms.ChoiceField(
        label="Attribute",
        choices=(
            (constants.BY_IP, "IP Address"),
            (constants.BY_HOSTNAME, "Hostname"),
            (constants.BY_HW_ADDRESS, "Hardware Address"),
            (constants.BY_CLIENT_ID, "Client ID"),
            (constants.BY_SUBNET, "Subnet"),
            (constants.BY_SUBNET_ID, "Subnet ID"),
        ),
        required=True,
    )

    class Meta:
        ip_version = 4


class Leases6SearchForm(BaseLeasesSarchForm):
    by = forms.ChoiceField(
        label="Attribute",
        choices=(
            (constants.BY_IP, "IP Address"),
            (constants.BY_HOSTNAME, "Hostname"),
            (constants.BY_DUID, "DUID"),
            (constants.BY_SUBNET, "Subnet"),
            (constants.BY_SUBNET_ID, "Subnet ID"),
        ),
        required=True,
    )

    class Meta:
        ip_version = 6


class MultipleIPField(forms.MultipleChoiceField):
    def __init__(self, version: Literal[6, 4], *args, **kwargs) -> None:
        self._version = version
        super().__init__(*args, widget=forms.MultipleHiddenInput, **kwargs)

    def clean(self, value: Any) -> Any:
        if not isinstance(value, list):
            raise forms.ValidationError(f"Expected a list, got {type(value)}.")

        if len(value) == 0:
            raise forms.ValidationError("IP address list is empty.")

        try:
            return [str(IPAddress(ip, version=self._version)) for ip in value]
        except (AddrFormatError, ValueError) as e:
            raise forms.ValidationError("Invalid IP address.") from e


class BaseLeaseDeleteForm(forms.Form):
    # NetBox v4.4 requires a background_job field for the bulk_delete.html
    # template.
    background_job = forms.CharField(
        required=False, widget=VeryHiddenInput, label="background_job"
    )
    return_url = forms.CharField(
        required=False,
        widget=forms.HiddenInput(),
    )


class Lease6DeleteForm(BaseLeaseDeleteForm):
    pk = MultipleIPField(6)


class Lease4DeleteForm(BaseLeaseDeleteForm):
    pk = MultipleIPField(4)

netbox_kea/templates/netbox_kea/exception_htmx.html
<div class="container-fluid">
  <div class="row">
    <div class="col col-md-6 offset-md-3">
      <div class="card border-danger mt-5">
        <h5 class="card-header"><i class="mdi mdi-alert"></i> Server Error</h5>
        <div class="card-body">
          <strong>{{ type_ }}</strong>: {{ exception }}
        </div>
      </div>
    </div>
  </div>
</div>

netbox_kea/templates/netbox_kea/server.html
{% extends "generic/object.html" %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Server</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Name</th>
              <td>{{ object.name }}</td>
            </tr>
            <tr>
              <th scope="row">Server URL</th>
              <td>{{ object.server_url }}</td>
            </tr>
            <tr>
              <th scope="row">DHCPv6</th>
              <td>{% checkmark object.dhcp6 %}</td>
            </tr>
            <tr>
              <th scope="row">DHCPv4</th>
              <td>{% checkmark object.dhcp4 %}</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="col col-md-6">
      {% include "inc/panels/tags.html" %}
    </div>
  </div>
{% endblock content %}

netbox_kea/templates/netbox_kea/server_dhcp_leases.html
{% extends "generic/object.html" %}
{% load helpers %}

{% block head %}
  {{ block.super }}
  <style type="text/css">
    .loading-indicator{
      display: none;
    }
    .htmx-request .loading-indicator{
      display: inline;
    }
    .htmx-request.loading-indicator{
      display: inline;
    }
    div.quicksearch{
      display: none
    }
  </style>
{% endblock %}

{% block content %}{% include "netbox_kea/server_dhcp_leases_htmx.html" with is_embedded=True %}{% endblock %}
{% block modals %}
  {{ block.super }}
  {% table_config_form table table_name="LeasesTable" %}
{% endblock %}

netbox_kea/templates/netbox_kea/server_dhcp_leases_htmx.html
{% load form_helpers %}
{% load helpers %}
{% load render_table from django_tables2 %}

<div id="lease-search" hx-target="#lease-search" hx-swap="outerHTML" hx-push-url="true">
  <div class="row px-3">
    <div class="col col-6 offset-3 py-3">
      <form
        class="form form-horizontal"
        hx-get="."
        hx-indicator="#search-indicator"
        hx-disabled-elt="#lease-search-btn"
        {% if form.is_bound and is_embedded and form.is_valid %}hx-trigger="load"{% endif %}
      >
        {% if form.cleaned_data.page %}
          {# Only include on full page load so that the user lands on the correct page. #}
          <input type="hidden" id="id_page" name="page" value="{{ form.cleaned_data.page }}">
        {% endif %}
        {% for e in form.errors.page %}
          <div class="alert alert-danger" role="alert">{{ e }}</div>
        {% endfor %}
        {% render_form form %}
        <div class="text-end">
          <div id="search-indicator" class="spinner-border d-inline-block align-middle htmx-indicator me-2" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
          <button id="lease-search-btn" type="submit" class="btn btn-primary">
            <span class="mdi mdi-magnify" aria-hidden="true"></span> Search
          </button>
        </div>
      </form>
    </div>
  </div>

  {% if not is_embedded and form.is_valid %}
    {% include "inc/table_controls_htmx.html" with table_modal="LeasesTable_config" %}
    {% with preferences|get_key:"pagination.placement" as paginator_placement %}
      <form method="post" action="{{ delete_action }}">
        {% csrf_token %}
        <input type="hidden" name="return_url" value="{{ request.path }}?{{ request.GET.urlencode }}" />
        <div class="card table-responsive">
          {% if paginator_placement == 'top' or paginator_placement == 'both' %}
            {% include "netbox_kea/inc/server_dhcp_leases_paginator.html" with table=table paginate=paginate placement="top" %}
          {% endif %}
          {% render_table table "inc/table_htmx.html" %}
          {% if paginator_placement != "top" %}
            {% include "netbox_kea/inc/server_dhcp_leases_paginator.html" with table=table paginate=paginate placement="bottom" %}
          {% endif %}
        </div>
        <div class="d-print-none d-flex justify-content-between mt-2">
          <div>
            {% if can_delete %}
              <button type="submit" class="btn btn-sm btn-danger"><i class="mdi mdi-trash-can-outline" aria-hidden="true"></i> Delete Selected</button>
            {% endif %}
          </div>

          <div class="dropdown">
            <button type="button" class="btn btn-purple dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="mdi mdi-download"></i> Export
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><a class="dropdown-item" href="{% querystring request export="table" %}">Current View</a></li>
              <li><a class="dropdown-item" href="{% querystring request export="" %}">All Data (CSV)</a></li>
            </ul>
          </div>
        </div>
      </form>
    {% endwith %}
  {% endif %}
</div>

netbox_kea/templates/netbox_kea/server_dhcp_subnets.html
{% extends "generic/object_children.html" %}

{% block head %}
  {{ block.super }}
  <style type="text/css">
    div.quicksearch{
      display: none
    }
    nav.text-end[aria-label="Pagination optoins"]{
      display: none
    }
  </style>
{% endblock %}

{% block bulk_controls %}
<div class="dropdown d-flex justify-content-end">
  <button type="button" class="btn btn-purple dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="mdi mdi-download"></i> Export
  </button>
  <ul class="dropdown-menu dropdown-menu-end">
    <li><a class="dropdown-item" href="?export=table">Current View</a></li>
    <li><a class="dropdown-item" href="?export">All Data (CSV)</a></li>
  </ul>
</div>
{% endblock bulk_controls %}

netbox_kea/templates/netbox_kea/server_status.html
{% extends "generic/object.html" %}

{% block content %}
  {% for name, service_data in statuses.items %}
    <div class="card">
      <h5 class="card-header">{{ name }}</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          {% for k,v in service_data.items %}
          <tr>
            <th scope="row">{{ k }}</th>
            <td>{% if k == "Version" %}<code>{{ v }}</code>{% else %}{{ v }}{% endif %}</td>
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  {% endfor %}
{% endblock %}